(self.AMP=self.AMP||[]).push({n:"amp-access",v:"2010010034001",f:(function(AMP,_){
'use strict';var h;function aa(a){for(var b=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global],c=0;c<b.length;++c){var d=b[c];if(d&&d.Math==Math)return}(function(){throw Error("Cannot find global object");})()}aa(this);"function"===typeof Symbol&&Symbol("x");var ba;function k(){return ba?ba:ba=Promise.resolve(void 0)};function m(){var a,b;this.promise=new Promise(function(c,d){a=c;b=d});this.resolve=a;this.reject=b};function ca(a,b){var c=b=void 0===b?"":b;try{return decodeURIComponent(a)}catch(d){return c}};var da=/(?:^[#?]?|&)([^=&]+)(?:=([^&]*))?/g;function q(a){var b=Object.create(null);if(!a)return b;for(var c;c=da.exec(a);){var d=ca(c[1],c[1]),e=c[2]?ca(c[2].replace(/\+/g," "),c[2]):"";b[d]=e}return b};var ea="";
function ia(){var a=self;if(a.__AMP_MODE)var b=a.__AMP_MODE;else{b=q(a.location.originalHash||a.location.hash);var c=q(a.location.search);ea||(ea=a.AMP_CONFIG&&a.AMP_CONFIG.v?a.AMP_CONFIG.v:"012010010034001");b={localDev:!1,development:!!(0<=["1","actions","amp","amp4ads","amp4email"].indexOf(b.development)||a.AMP_DEV_MODE),examiner:"2"==b.development,esm:!1,geoOverride:b["amp-geo"],minified:!0,lite:void 0!=c.amp_lite,test:!1,log:b.log,version:"2010010034001",rtvVersion:ea};b=a.__AMP_MODE=b}return b}
;var ja=Object.prototype.toString;var w=self.AMP_CONFIG||{},ka=("string"==typeof w.cdnProxyRegex?new RegExp(w.cdnProxyRegex):w.cdnProxyRegex)||/^https:\/\/([a-zA-Z0-9_-]+\.)?cdn\.ampproject\.org$/;function la(a){if(!self.document||!self.document.head||self.location&&ka.test(self.location.origin))return null;var b=self.document.head.querySelector('meta[name="'+a+'"]');return b&&b.getAttribute("content")||null}
var ma={thirdParty:w.thirdPartyUrl||"https://3p.ampproject.net",thirdPartyFrameHost:w.thirdPartyFrameHost||"ampproject.net",thirdPartyFrameRegex:("string"==typeof w.thirdPartyFrameRegex?new RegExp(w.thirdPartyFrameRegex):w.thirdPartyFrameRegex)||/^d-\d+\.ampproject\.net$/,cdn:w.cdnUrl||la("runtime-host")||"https://cdn.ampproject.org",cdnProxyRegex:ka,localhostRegex:/^https?:\/\/localhost(:\d+)?$/,errorReporting:w.errorReportingUrl||"https://us-central1-amp-error-reporting.cloudfunctions.net/r",betaErrorReporting:w.betaErrorReportingUrl||
"https://us-central1-amp-error-reporting.cloudfunctions.net/r-beta",localDev:w.localDev||!1,trustedViewerHosts:[/(^|\.)google\.(com?|[a-z]{2}|com?\.[a-z]{2}|cat)$/,/(^|\.)gmail\.(com|dev)$/],geoApi:w.geoApiUrl||la("amp-geo-api")};self.__AMP_LOG=self.__AMP_LOG||{user:null,dev:null,userForEmbed:null};var x=self.__AMP_LOG;function z(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function A(){if(x.dev)return x.dev;throw Error("failed to call initLogConstructor");}function B(a,b,c,d,e){return z().assert(a,b,c,d,e,void 0,void 0,void 0,void 0,void 0,void 0)};var na=Object.prototype.hasOwnProperty;function E(a){return a||{}};function H(){this.Ya=100;this.sa=this.Da=0;this.ga=Object.create(null)}H.prototype.has=function(a){return!!this.ga[a]};H.prototype.get=function(a){var b=this.ga[a];if(b)return b.access=++this.sa,b.payload};H.prototype.put=function(a,b){this.has(a)||this.Da++;this.ga[a]={payload:b,access:this.sa};if(!(this.Da<=this.Ya)){A().warn("lru-cache","Trimming LRU cache");a=this.ga;var c=this.sa+1,d;for(d in a){var e=a[d].access;if(e<c){c=e;var f=d}}void 0!==f&&(delete a[f],this.Da--)}};var oa=E({c:!0,v:!0,a:!0,ad:!0}),pa,qa,ra=/[?&]amp_js[^&]*/,sa=/[?&]amp_gsa[^&]*/,ta=/[?&]amp_r[^&]*/,ua=/[?&]amp_kit[^&]*/,va=/[?&]usqp[^&]*/;
function K(a){pa||(pa=self.document.createElement("a"),qa=self.__AMP_URL_CACHE||(self.__AMP_URL_CACHE=new H));var b=qa,c=pa;if(b&&b.has(a))a=b.get(a);else{c.href=a;c.protocol||(c.href=c.href);var d={href:c.href,protocol:c.protocol,host:c.host,hostname:c.hostname,port:"0"==c.port?"":c.port,pathname:c.pathname,search:c.search,hash:c.hash,origin:null};"/"!==d.pathname[0]&&(d.pathname="/"+d.pathname);if("http:"==d.protocol&&80==d.port||"https:"==d.protocol&&443==d.port)d.port="",d.host=d.hostname;d.origin=
c.origin&&"null"!=c.origin?c.origin:"data:"!=d.protocol&&d.host?d.protocol+"//"+d.host:d.href;b&&b.put(a,d);a=d}return a}function wa(a){var b=[],c;for(c in a){var d=a[c];if(null!=d)if(Array.isArray(d))for(var e=0;e<d.length;e++){var f=d[e];b.push(encodeURIComponent(c)+"="+encodeURIComponent(f))}else e=d,b.push(encodeURIComponent(c)+"="+encodeURIComponent(e))}return b.join("&")}
function L(a,b){var c=void 0===c?"source":c;B(null!=a,"%s %s must be available",b,c);var d=a;"string"==typeof d&&(d=K(d));var e;(e="https:"==d.protocol||"localhost"==d.hostname||"127.0.0.1"==d.hostname)||(d=d.hostname,e=d.length-10,e=0<=e&&d.indexOf(".localhost",e)==e);B(e||/^(\/\/)/.test(a),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,a)}function M(a){var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}
function N(a){"string"==typeof a&&(a=K(a));return ma.cdnProxyRegex.test(a.origin)}
function xa(a){"string"==typeof a&&(a=K(a));if(!N(a))return a.href;var b=a.pathname.split("/");B(oa[b[1]],"Unknown path prefix in url %s",a.href);var c=b[2],d="s"==c?"https://"+decodeURIComponent(b[3]):"http://"+decodeURIComponent(c);B(0<d.indexOf("."),"Expected a . in origin %s",d);b.splice(1,"s"==c?3:2);b=d+b.join("/");d=(d=a.search)&&"?"!=d?(d=d.replace(ra,"").replace(sa,"").replace(ta,"").replace(ua,"").replace(va,"").replace(/^[?&]/,""))?"?"+d:"":"";return b+d+(a.hash||"")};function O(a){if(a.__AMP__EXPERIMENT_TOGGLES)return a.__AMP__EXPERIMENT_TOGGLES;a.__AMP__EXPERIMENT_TOGGLES=Object.create(null);var b=a.__AMP__EXPERIMENT_TOGGLES;if(a.AMP_CONFIG)for(var c in a.AMP_CONFIG){var d=a.AMP_CONFIG[c];"number"===typeof d&&0<=d&&1>=d&&(b[c]=Math.random()<d)}if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-doc-opt-in"])&&0<a.AMP_CONFIG["allow-doc-opt-in"].length){var e=a.AMP_CONFIG["allow-doc-opt-in"],f=a.document.head.querySelector('meta[name="amp-experiments-opt-in"]');
if(f){var g=f.getAttribute("content").split(",");for(c=0;c<g.length;c++)-1!=e.indexOf(g[c])&&(b[g[c]]=!0)}}Object.assign(b,ya(a));if(a.AMP_CONFIG&&Array.isArray(a.AMP_CONFIG["allow-url-opt-in"])&&0<a.AMP_CONFIG["allow-url-opt-in"].length){c=a.AMP_CONFIG["allow-url-opt-in"];a=q(a.location.originalHash||a.location.hash);for(var l=0;l<c.length;l++){var n=a["e-"+c[l]];"1"==n&&(b[c[l]]=!0);"0"==n&&(b[c[l]]=!1)}}return b}
function ya(a){var b="";try{"localStorage"in a&&(b=a.localStorage.getItem("amp-experiment-toggles"))}catch(e){A().warn("EXPERIMENTS","Failed to retrieve experiments from localStorage.")}var c=b?b.split(/\s*,\s*/g):[];a=Object.create(null);for(var d=0;d<c.length;d++)0!=c[d].length&&("-"==c[d][0]?a[c[d].substr(1)]=!1:a[c[d]]=!0);return a};function za(a,b){var c=a.ownerDocument.defaultView,d=c.__AMP_TOP||(c.__AMP_TOP=c),e=c!=d,f=!!O(d)["ampdoc-fie"];e&&!f?b=P(c,b)?S(c,b):null:(a=T(a),a=U(a),b=P(a,b)?S(a,b):null);return b}function V(a,b){a=a.__AMP_TOP||(a.__AMP_TOP=a);return S(a,b)}function Aa(a){a=a.__AMP_TOP||(a.__AMP_TOP=a);return P(a,"performance")?S(a,"performance"):null}function W(a,b){var c=T(a);c=U(c);return S(c,b)}function T(a){return a.nodeType?V((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}
function U(a){a=T(a);return a.isSingleDoc()?a.win:a}function S(a,b){P(a,b);a=Ba(a)[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function Ca(a,b){var c=Da(a,b);if(c)return c;a=Ba(a);a[b]=Ea();return a[b].promise}function Da(a,b){var c=Ba(a)[b];if(c){if(c.promise)return c.promise;S(a,b);return c.promise=Promise.resolve(c.obj)}return null}function Ba(a){var b=a.__AMP_SERVICES;b||(b=a.__AMP_SERVICES={});return b}
function P(a,b){a=a.__AMP_SERVICES&&a.__AMP_SERVICES[b];return!(!a||!a.ctor&&!a.obj)}function Ea(){var a=new m,b=a.promise,c=a.resolve;a=a.reject;b.catch(function(){});return{obj:null,promise:b,resolve:c,reject:a,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
var Fa=/(\0)|^(-)$|([\x01-\x1f\x7f]|^-?[0-9])|([\x80-\uffff0-9a-zA-Z_-]+)|[^]/g;function Ga(a,b,c,d,e){return e?e:b?"\ufffd":d?a.slice(0,-1)+"\\"+a.slice(-1).charCodeAt(0).toString(16)+" ":"\\"+a};function Ha(a,b,c){try{var d=a.open(b,"_blank",c)}catch(g){A().error("DOM","Failed to open url on target: ","_blank",g)}var e;if(!(e=d||!1)){e=c||"";var f;"number"!==typeof f&&(f=0);e=f+8>e.length?!1:-1!==e.indexOf("noopener",f)}e||(d=a.open(b,"_top"));return d}function Ia(a){return"SCRIPT"==a.tagName&&a.hasAttribute("type")&&"APPLICATION/JSON"==a.getAttribute("type").toUpperCase()};function Ja(a){var b=Da(U(a),"amp-analytics-instrumentation");if(b)return b;var c=T(a);return c.waitForBodyOpen().then(function(){var a=c.win;var b=c.win.document.head;if(b){var f={};b=b.querySelectorAll("script[custom-element],script[custom-template]");for(var g=0;g<b.length;g++){var l=b[g];l=l.getAttribute("custom-element")||l.getAttribute("custom-template");f[l]=!0}f=Object.keys(f)}else f=[];return f.includes("amp-analytics")?V(a,"extensions").waitForExtension(a,"amp-analytics"):k()}).then(function(){var b=
c.win;return b.__AMP_EXTENDED_ELEMENTS&&b.__AMP_EXTENDED_ELEMENTS["amp-analytics"]?Ca(U(a),"amp-analytics-instrumentation"):null})};function X(a){return V(a,"timer")};function Y(a,b,c){this.ampdoc=a;this.B=c;this.S=B(b.authorization,'"authorization" URL must be specified');L(this.S,'"authorization"');this.X=!b.noPingback;this.oa=b.pingback;this.X&&(B(this.oa,'"pingback" URL must be specified'),L(this.oa,'"pingback"'));b.authorizationTimeout?(c=b.authorizationTimeout,B("number"==typeof c,'"authorizationTimeout" must be a number'),ia().development||(c=Math.min(c,3E3))):c=3E3;this.ua=c;this.P=V(a.win,"xhr");this.A=X(a.win)}h=Y.prototype;
h.getConfig=function(){return{authorizationUrl:this.S,pingbackEnabled:this.X,pingbackUrl:this.oa,authorizationTimeout:this.ua}};h.getAuthorizationUrl=function(){return this.S};h.isAuthorizationEnabled=function(){return!0};h.getAuthorizationTimeout=function(){return this.ua};
h.authorize=function(){var a=this;A().fine("amp-access-client","Start authorization via ",this.S);return this.B.buildUrl(this.S,!1).then(function(b){A().fine("amp-access-client","Authorization URL: ",b);return a.A.timeoutPromise(a.ua,a.P.fetchJson(b,{credentials:"include"})).then(function(a){return a.json()})})};h.isPingbackEnabled=function(){return this.X};
h.pingback=function(){var a=this;return this.B.buildUrl(this.oa,!0).then(function(b){A().fine("amp-access-client","Pingback URL: ",b);return a.P.sendSignal(b,{method:"POST",credentials:"include",headers:E({"Content-Type":"application/x-www-form-urlencoded"}),body:""})})};h.postAction=function(){};function Ka(a,b,c){this.Xa=a;this.Ea=b;this.o=c;this.N=this.Fa=null;this.La=this.fb.bind(this);this.lb=0;this.Ha={}}h=Ka.prototype;h.connect=function(a){if(this.N)throw Error("already connected");this.N=a;this.Xa.addEventListener("message",this.La)};h.disconnect=function(){this.N&&(this.N=null,this.Xa.removeEventListener("message",this.La))};h.isConnected=function(){return null!=this.o};h.getTarget=function(){var a=La(this);if(!a)throw Error("not connected");return a};
function La(a){a.N&&!a.Fa&&(a.Fa="function"==typeof a.Ea?a.Ea():a.Ea);return a.Fa}h.getTargetOrigin=function(){if(null==this.o)throw Error("not connected");return this.o};h.sendCommand=function(a,b){Ma(this,void 0,a,b)};h.sendCommandRsvp=function(a,b){var c=String(++this.lb),d=null,e=new Promise(function(a){d=a});this.Ha[c]={promise:e,resolver:d};Ma(this,c,a,b);return e};
function Ma(a,b,c,d){var e=a.getTarget();a="connect"==c?null!=a.o?a.o:"*":a.getTargetOrigin();e.postMessage({sentinel:"__AMP__",_rsvp:b,cmd:c,payload:d||null},a)}
h.fb=function(a){var b=this,c=a.data;if(c&&"__AMP__"==c.sentinel){var d=a.origin,e=c.cmd,f=c.payload||null;null==this.o&&"start"==e&&(this.o=d);null==this.o&&a.source&&La(this)==a.source&&(this.o=d);if(d==this.o){var g=c._rsvp,l=!!g&&"rsvp"!=e;a=this.xa(g,e,f);l&&Promise.resolve(a).then(function(a){Ma(b,g,"rsvp",{result:a})},function(a){Ma(b,g,"rsvp",{error:String(a)})})}}};
h.xa=function(a,b,c){if("rsvp"==b){var d=a&&this.Ha[a];d&&("error"in c?d.resolver(Promise.reject(Error(c.error))):d.resolver(c.result),delete this.Ha[a])}else return this.N(b,c)};function Na(a,b){if("."==b)return a;b=b.split(".");for(var c=0;c<b.length;c++){var d=b[c];if(d&&a&&void 0!==a[d]&&(null==a||"object"!=typeof a?0:Object.prototype.hasOwnProperty.call(a,d)))a=a[d];else{a=void 0;break}}return a}function Oa(a,b){try{return JSON.parse(a)}catch(c){return b&&b(c),null}};function Pa(a){var b=!1;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","")};function Qa(a,b,c){var d=this;this.ampdoc=a;this.B=c;this.$a=b;this.A=X(a.win);this.la=B(b.iframeSrc,'"iframeSrc" URL must be specified');L(this.la,'"iframeSrc"');(this.V=b.iframeVars||null)&&B(Array.isArray(this.V),'"iframeVars" must be an array');this.ab=B(b.defaultResponse,'"defaultResponse" must be specified');this.o=K(this.la).origin;this.va=this.ha=null;this.W=a.win.document.createElement("iframe");Pa(this.W);this.$=new Ka(this.ampdoc.win,function(){return d.W.contentWindow},this.o);this.Na=
null}h=Qa.prototype;h.disconnect=function(){this.$.disconnect();this.ampdoc.getBody().removeChild(this.W)};h.getConfig=function(){return{iframeSrc:this.la,iframeVars:this.V}};h.isAuthorizationEnabled=function(){return!0};h.authorize=function(){return Promise.race([Ra(this),Sa(this)])};h.isPingbackEnabled=function(){return!0};h.pingback=function(){var a=this;return this.connect().then(function(){return a.$.sendCommandRsvp("pingback",{})})};h.postAction=function(){Ta(this,null)};
h.connect=function(){if(!this.va){var a=new m;this.va=a.promise;this.ha=a.resolve;this.Na=Ua(this);this.$.connect(this.xa.bind(this));this.ampdoc.getBody().appendChild(this.W);this.W.src=this.la}return this.va};function Ua(a){return new Promise(function(b){var c=JSON.parse(JSON.stringify(a.$a));if(a.V){var d=a.V.join("&"),e=a.B.collectUrlVars(d,!1);b(e.then(function(a){c.iframeVars=a;return c}))}else b(c)})}
function Ra(a){var b=3E3*(ia().development?2:1);return a.A.promise(b).then(function(){return Va(a)||a.ab})}function Sa(a){return a.connect().then(function(){return a.$.sendCommandRsvp("authorize",{})}).then(function(b){b&&k().then(function(){return Ta(a,b)});return b})}
function Va(a){var b=a.ampdoc.win,c=b.sessionStorage||b.localStorage;if(!c)return null;try{var d=c.getItem("amp-access-iframe");if(!d)return null;var e=JSON.parse(d);return e.t+6048E5<a.ampdoc.win.Date.now()?null:e.d||null}catch(f){A().error("amp-access-iframe","failed to restore access response: ",f);try{c.removeItem("amp-access-iframe")}catch(g){}return null}}
function Ta(a,b){var c=a.ampdoc.win;if(c=c.sessionStorage||c.localStorage)try{b?c.setItem("amp-access-iframe",JSON.stringify(E({t:a.ampdoc.win.Date.now(),d:b}))):c.removeItem("amp-access-iframe")}catch(d){A().error("amp-access-iframe","failed to store access response: ",d)}}h.xa=function(a){var b=this;"connect"==a&&this.Na.then(function(a){b.$.sendCommandRsvp("start",{protocol:"amp-access",config:a}).then(function(){b.ha&&(b.ha(),b.ha=null)})})};function Wa(a,b,c){this.ampdoc=a;this.B=c;this.ta=b.authorizationFallbackResponse||null;this.C=N(a.win.location)}h=Wa.prototype;h.getConfig=function(){return{authorizationResponse:this.ta}};h.isAuthorizationEnabled=function(){return!!this.ta&&!this.C};h.authorize=function(){A().fine("amp-access-other","Use the authorization fallback for type=other");return Promise.resolve(this.ta)};h.isPingbackEnabled=function(){return!1};h.pingback=function(){A().fine("amp-access-other","Ignore pingback");return k()};
h.postAction=function(){};var Xa=["GET","POST"];function Ya(a,b){var c=Object.assign({},b),d=b.body;if(d&&"function"==typeof d.getFormData){var e=b.body;c.headers["Content-Type"]="multipart/form-data;charset=utf-8";b=e.entries();d=[];for(var f=b.next();!f.done;f=b.next())d.push(f.value);c.body=d}return{input:a,init:c}}
function Za(a,b){B("[object Object]"===ja.call(a),"Object expected: %s",a);if("document"!=b)return new Response(a.body,a.init);var c=Object.create(null),d={status:200,statusText:"OK",getResponseHeader:function(a){return c[String(a).toLowerCase()]||null}};if(a.init){var e=a.init;Array.isArray(e.headers)&&e.headers.forEach(function(a){var b=a[1];c[String(a[0]).toLowerCase()]=String(b)});e.status&&(d.status=parseInt(e.status,10));e.statusText&&(d.statusText=String(e.statusText))}return new Response(a.body?
String(a.body):"",d)}
function $a(a,b,c,d){if(!b)return k();var e=d.prerenderSafe?k():b.whenFirstVisible(),f=W(b,"viewer"),g=N(c),l=f.hasCapability("xhrInterceptor"),n=d.bypassInterceptorForDev&&!1;return g||!l||n||!b.getRootNode().documentElement.hasAttribute("allow-xhr-interception")?e:e.then(function(){return f.isTrustedViewer()}).then(function(b){if(b||O(a)["untrusted-xhr-interception"]){var e=E({originalRequest:Ya(c,d)});return f.sendMessageAwaitResponse("xhr",e).then(function(a){return Za(a,d.responseType)})}})}
function ab(a,b,c){!1!==c.ampCors&&(c=K(b),c=q(c.search),B(!("__amp_source_origin"in c),"Source origin is not allowed in %s",b),a=K(xa(a.location.href)).origin,a=encodeURIComponent("__amp_source_origin")+"="+encodeURIComponent(a),a&&(b=b.split("#",2),c=b[0].split("?",2),a=c[0]+(c[1]?"?"+c[1]+"&"+a:"?"+a),b=a+=b[1]?"#"+b[1]:""));return b}
function bb(a){a=a||{};var b=a.method;void 0===b?b="GET":(b=b.toUpperCase(),Xa.includes(b));a.method=b;a.headers=a.headers||E({});a.headers.Accept="text/html";return a}function cb(a,b,c){c=c||{};var d=a.origin||K(a.location.href).origin;a=K(b).origin;d==a&&(c.headers=c.headers||{},c.headers["AMP-Same-Origin"]="true");return c}
function db(a){return new Promise(function(b){if(a.ok)return b(a);b=a.status;var c=z().createError("HTTP error "+b);c.retriable=415==b||500<=b&&600>b;c.response=a;throw c;})};function eb(a,b,c){var d=bb(c);d=cb(a,b,d);b=ab(a,b,d);var e=V(a,"ampdoc");c=e.isSingleDoc()?e.getSingleDoc():null;d.responseType="document";return $a(a,c,b,d).then(function(a){return a?a.text().then(function(a){return(new DOMParser).parseFromString(a,"text/html")}):hb(b,d).then(function(a){return a.xhr.responseXML})})}
function hb(a,b){return new Promise(function(c,d){var e=new XMLHttpRequest;e.open(b.method||"GET",a,!0);e.withCredentials="include"==b.credentials;e.responseType="document";for(var f in b.headers)e.setRequestHeader(f,b.headers[f]);e.onreadystatechange=function(){if(!(2>e.readyState))if(100>e.status||599<e.status)e.onreadystatechange=null,d(z().createExpectedError("Unknown HTTP status "+e.status));else if(4==e.readyState){var a={status:e.status,statusText:e.statusText,headers:ib(e.getAllResponseHeaders())};
a=new Response("",a);a=db(a).then(function(a){return{response:a,xhr:e}});c(a)}};e.onerror=function(){d(z().createExpectedError("Request failure"))};e.onabort=function(){d(z().createExpectedError("Request aborted"))};"POST"==b.method?e.send(b.body):e.send()})}function ib(a){var b=E({});a.replace(/\r?\n[\t ]+/g," ").split(/\r?\n/).forEach(function(a){var c=a.split(":"),e=c.shift().trim();e&&(c=c.join(":").trim(),b[e]=c)});return b};function jb(a,b,c){this.ampdoc=a;this.B=c;this.l=new Y(a,b,c);this.P=V(a.win,"xhr");this.A=X(a.win);this.O=V(a.win,"vsync");this.D=a.getMetaByName("i-amphtml-access-state");var d=!!O(a.win)["amp-access-server"];this.C=N(a.win.location)||d;this.ca=(d?a.getParam("serverAccessService"):null)||M(a.win.location.href)}h=jb.prototype;h.getConfig=function(){return{client:this.l.getConfig(),proxy:this.C,serverState:this.D}};h.isAuthorizationEnabled=function(){return!0};
h.authorize=function(){var a=this;A().fine("amp-access-server","Start authorization with ",this.C?"proxy":"non-proxy",this.D,this.l.getAuthorizationUrl());if(!this.C||!this.D)return A().fine("amp-access-server","Proceed via client protocol"),this.l.authorize();A().fine("amp-access-server","Proceed via server protocol");return this.B.collectUrlVars(this.l.getAuthorizationUrl(),!1).then(function(b){var c={},d;for(d in b)null!=b[d]&&(c[d]=String(b[d]));b=E({url:M(a.ampdoc.win.location.href),state:a.D,
vars:c});A().fine("amp-access-server","Authorization request: ",a.ca,b);return a.A.timeoutPromise(a.l.getAuthorizationTimeout(),eb(a.ampdoc.win,a.ca,{method:"POST",body:"request="+encodeURIComponent(JSON.stringify(b)),headers:E({"Content-Type":"application/x-www-form-urlencoded"})}))}).then(function(b){A().fine("amp-access-server","Authorization response: ",b);var c=b.querySelector('script[id="amp-access-data"]').textContent,d=JSON.parse(c);A().fine("amp-access-server","- access data: ",d);return a.Ca(b).then(function(){return d})})};
h.isPingbackEnabled=function(){return this.l.isPingbackEnabled()};h.pingback=function(){return this.l.pingback()};h.postAction=function(){};
h.Ca=function(a){var b=this,c=a.querySelectorAll("[i-amphtml-access-id]");A().fine("amp-access-server","- access sections: ",c);return this.O.mutatePromise(function(){for(var a=0;a<c.length;a++){var e=c[a],f=e.getAttribute("i-amphtml-access-id"),g=b.ampdoc.getRootNode().querySelector('[i-amphtml-access-id="'+String(f).replace(Fa,Ga)+'"]');g?g.parentElement.replaceChild(b.ampdoc.win.document.importNode(e,!0),g):A().warn("amp-access-server","Section not found: ",f)}})};function kb(a){if("undefined"!==typeof TextDecoder)return(new TextDecoder("utf-8")).decode(a);a=new Uint8Array(a.buffer||a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=String.fromCharCode(a[c]);a=b.join("");return decodeURIComponent(escape(a))}function lb(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;c++){var d=a.charCodeAt(c);b[c]=d}return b};var mb={"-":"+",_:"/",".":"="};function nb(a){var b=atob(a.replace(/[-_.]/g,function(a){return mb[a]}));return lb(b)};function ob(a){a=a.trim();a=a.replace(/^\-+BEGIN[^-]*\-+/,"");a=a.replace(/\-+END[^-]*\-+$/,"");a=a.replace(/[\r\n]/g,"").trim();return lb(atob(a))};function pb(a){this.win=a;this.qa=a.crypto&&(a.crypto.subtle||a.crypto.webkitSubtle)||null}pb.prototype.decode=function(a){return qb(a).payload};pb.prototype.isVerificationSupported=function(){return!!this.qa};
pb.prototype.decodeAndVerify=function(a,b){var c=this;if(!this.qa)throw Error("Crypto is not supported on this platform");return(new Promise(function(b){return b(qb(a))})).then(function(a){var d=a.header.alg;if(!d||"RS256"!=d)throw Error("Only alg=RS256 is supported");return rb(c,b).then(function(b){var d=nb(a.sig);return c.qa.verify({name:"RSASSA-PKCS1-v1_5"},b,d,lb(a.verifiable))}).then(function(b){if(b)return a.payload;throw Error("Signature verification failed");})})};
function qb(a){function b(){throw Error('Invalid token: "'+a+'"');}var c=a.split(".");3!=c.length&&b();var d=nb(c[0]),e=nb(c[1]);return{header:Oa(kb(d),b),payload:Oa(kb(e),b),verifiable:c[0]+"."+c[1],sig:c[2]}}function rb(a,b){return b.then(function(b){return a.qa.importKey("spki",ob(b),{name:"RSASSA-PKCS1-v1_5",hash:{name:"SHA-256"}},!1,["verify"])})};function sb(a,b,c){this.ampdoc=a;this.B=c;this.l=new Y(a,b,c);this.P=V(a.win,"xhr");this.A=X(a.win);this.O=V(a.win,"vsync");this.D=a.getMetaByName("i-amphtml-access-state");c=!!O(a.win)["amp-access-server-jwt"];this.C=N(a.win.location)||c;this.ca=(c?a.getParam("serverAccessService"):null)||M(a.win.location.href);this.Y=b.publicKey||null;this.L=b.publicKeyUrl||null;B(this.Y||this.L,'"publicKey" or "publicKeyUrl" must be specified');this.L&&L(this.L,'"publicKeyUrl"');this.Y&&this.L&&z().warn("amp-access-server-jwt",
'Both "publicKey" and "publicKeyUrl" specified. The "publicKeyUrl" will be ignored.');this.ya=new pb(a.win)}h=sb.prototype;h.getConfig=function(){return{client:this.l.getConfig(),proxy:this.C,serverState:this.D,publicKey:this.Y,publicKeyUrl:this.L}};h.isAuthorizationEnabled=function(){return!0};h.authorize=function(){A().fine("amp-access-server-jwt","Start authorization with ",this.C?"proxy":"non-proxy",this.D,this.l.getAuthorizationUrl());return this.C&&this.D?tb(this):ub(this)};
h.isPingbackEnabled=function(){return this.l.isPingbackEnabled()};h.pingback=function(){return this.l.pingback()};h.postAction=function(){};
function vb(a){var b=a.B.buildUrl(a.l.getAuthorizationUrl(),!1).then(function(b){A().fine("amp-access-server-jwt","Authorization URL: ",b);return a.A.timeoutPromise(3E3,a.P.fetchText(b,{credentials:"include"}))}).then(function(a){return a.text()}).then(function(b){var c=a.ya.decode(b);B(c.amp_authdata,'"amp_authdata" must be present in JWT');return{encoded:b,jwt:c}});ia().development&&(a.ya.isVerificationSupported()?b=b.then(function(b){return a.ya.decodeAndVerify(b.encoded,wb(a)).then(function(){return b})}):
z().warn("amp-access-server-jwt","Cannot verify signature on this browser since it doesn't support WebCrypto APIs"),b=b.then(function(a){var b=a.jwt,c=Date.now(),f=b.exp;B(f,'"exp" field must be specified');B(1E3*parseFloat(f)>c,"token has expired: %s",f);b=b.aud;B(b,'"aud" field must be specified');c=!1;if(Array.isArray(b))for(f=0;f<b.length;f++){if("ampproject.org"==b[f]){c=!0;break}}else c="ampproject.org"==b;B(c,'"aud" must be "%s": %s',"ampproject.org",b);return a}));return b.catch(function(a){throw z().createError("JWT fetch or validation failed: ",
a);})}function wb(a){return a.Y?Promise.resolve(a.Y):a.P.fetchText(a.L).then(function(a){return a.text()})}function ub(a){A().fine("amp-access-server-jwt","Proceed via client protocol via ",a.l.getAuthorizationUrl());return vb(a).then(function(a){return a.jwt.amp_authdata})}
function tb(a){A().fine("amp-access-server-jwt","Proceed via server protocol");return vb(a).then(function(b){var c=b.encoded,d=b.jwt.amp_authdata;b=wa(E({url:M(a.ampdoc.win.location.href),state:a.D,jwt:c}));A().fine("amp-access-server-jwt","Authorization request: ",a.ca,b);A().fine("amp-access-server-jwt","- access data: ",d);return a.A.timeoutPromise(3E3,eb(a.ampdoc.win,a.ca,{method:"POST",body:b,headers:E({"Content-Type":"application/x-www-form-urlencoded"})})).then(function(b){A().fine("amp-access-server-jwt",
"Authorization response: ",b);return a.Ca(b)}).then(function(){return d})})}
h.Ca=function(a){var b=this,c=a.querySelectorAll("[i-amphtml-access-id]");A().fine("amp-access-server-jwt","- access sections: ",c);return this.O.mutatePromise(function(){for(var a=0;a<c.length;a++){var e=c[a],f=e.getAttribute("i-amphtml-access-id"),g=b.ampdoc.getRootNode().querySelector('[i-amphtml-access-id="'+String(f).replace(Fa,Ga)+'"]');g?g.parentElement.replaceChild(b.ampdoc.win.document.importNode(e,!0),g):A().warn("amp-access-server-jwt","Section not found: ",f)}})};function xb(a,b){this.ampdoc=a;this.ra=B(b.vendor,'"vendor" name must be specified');this.ob=b[this.ra]||{};this.X=!b.noPingback;a=new m;this.Va=a.promise;this.Ga=a.resolve}h=xb.prototype;h.getVendorName=function(){return this.ra};h.getConfig=function(){return this.ob};h.registerVendor=function(a){B(this.Ga,"Vendor has already been registered");this.Ga(a);this.Ga=null};h.isAuthorizationEnabled=function(){return!0};
h.authorize=function(){A().fine("amp-access-vendor","Start authorization via ",this.ra);return this.Va.then(function(a){return a.authorize()})};h.isPingbackEnabled=function(){return this.X};h.pingback=function(){A().fine("amp-access-vendor","Pingback via ",this.ra);return this.Va.then(function(a){return a.pingback()})};h.postAction=function(){};var Z;function yb(a,b,c){var d=a,e=c;var f=function(a){try{return e(a)}catch(n){throw self.__AMP_REPORT_ERROR(n),n;}};var g=zb();d.addEventListener(b,f,g?void 0:!1);return function(){d&&d.removeEventListener(b,f,g?void 0:!1);f=d=e=null}}function zb(){if(void 0!==Z)return Z;Z=!1;try{var a={get capture(){Z=!0}};self.addEventListener("test-options",null,a);self.removeEventListener("test-options",null,a)}catch(b){}return Z};function Ab(a,b){return yb(a,"message",b)}function Bb(a,b){var c=b,d=yb(a,"click",function(a){try{c(a)}finally{c=null,d()}});return d};var Cb=/RETURN_URL/;function Db(a,b){var c=W(a,"viewer");return parseInt(a.getParam("dialog"),10)?new Eb(c,b):new Fb(a.win,c,b)}function Gb(a,b){return Db(a,b).open()}function Eb(a,b){this.viewer=a;this.urlOrPromise=b}Eb.prototype.getLoginUrl=function(){return("string"==typeof this.urlOrPromise?Promise.resolve(this.urlOrPromise):this.urlOrPromise).then(function(a){return Hb(a,"RETURN_URL")})};
Eb.prototype.open=function(){var a=this;return this.getLoginUrl().then(function(b){A().fine("amp-access-login","Open viewer dialog: ",b);return a.viewer.sendMessageAwaitResponse("openDialog",E({url:b}))})};function Fb(a,b,c){this.win=a;this.viewer=b;this.urlOrPromise=c;this.ma=this.K=this.T=this.w=this.Ba=this.ba=null}
Fb.prototype.open=function(){var a=this;B(!this.ba,"Dialog already opened");return(new Promise(function(b,c){a.ba=b;a.Ba=c;Ib(a)})).then(function(b){Jb(a);return b},function(b){Jb(a);throw b;})};function Jb(a){a.ba=null;a.Ba=null;if(a.w){try{a.w.close()}catch(b){}a.w=null}a.K&&(a.win.clearInterval(a.K),a.K=null);a.ma&&(a.ma(),a.ma=null)}
Fb.prototype.getLoginUrl=function(){var a=this;return("string"==typeof this.urlOrPromise?Promise.resolve(this.urlOrPromise):this.urlOrPromise).then(function(b){return Hb(b,Kb(a))})};
function Ib(a){var b=a.win.screen,c=Math.floor(Math.min(700,.9*b.width)),d=Math.floor(Math.min(450,.9*b.height)),e=Math.floor((b.width-c)/2);b=Math.floor((b.height-d)/2);var f="height="+d+",width="+c+",left="+e+",top="+b+",resizable=yes,scrollbars=yes",g=Kb(a);a.T=null;if("string"==typeof a.urlOrPromise){var l=Hb(a.urlOrPromise,g);A().fine("amp-access-login","Open dialog: ",l,g,c,d,e,b);a.w=Ha(a.win,l,f);a.w&&(a.T=k())}else A().fine("amp-access-login","Open dialog: ","about:blank",g,c,d,e,b),a.w=
Ha(a.win,"",f),a.w&&(a.T=a.urlOrPromise.then(function(b){b=Hb(b,g);A().fine("amp-access-login","Set dialog url: ",b);a.w.location.replace(b)},function(a){throw Error("failed to resolve url: "+a);}));a.T?a.T.then(function(){Lb(a,g)},function(b){Mb(a,null,b)}):Mb(a,null,Error("failed to open dialog"))}
function Lb(a,b){var c=K(b).origin;a.K=a.win.setInterval(function(){a.w.closed&&(a.win.clearInterval(a.K),a.K=null,a.win.setTimeout(function(){Mb(a,"")},3E3))},500);a.ma=Ab(a.win,function(b){A().fine("amp-access-login","MESSAGE:",b);b.origin==c&&b.data&&"amp"==b.data.sentinel&&(A().fine("amp-access-login","Received message from dialog: ",b.data),"result"==b.data.type&&(a.w&&a.w.postMessage(E({sentinel:"amp",type:"result-ack"}),c),Mb(a,b.data.result)))})}
function Mb(a,b,c){a.ba&&(A().fine("amp-access-login","Login done: ",b,c),c?a.Ba(c):a.ba(b),Jb(a))}function Kb(a){var b=a.viewer.getResolvedViewerUrl();return ma.cdn+"/v0/amp-login-done-0.1.html?url="+encodeURIComponent(b)}function Hb(a,b){return Cb.test(a)?a.replace(Cb,encodeURIComponent(b)):a+(-1==a.indexOf("?")?"?":"&")+"return="+encodeURIComponent(b)};function Nb(a,b){var c=void 0,d=!1;c=void 0===c?{}:c;d=void 0===d?!0:d;var e=c,f=d;Ja(a).then(function(c){c&&c.triggerEventForTarget(a,b,e,f)})};var Ob={CLIENT:"client",IFRAME:"iframe",SERVER:"server",VENDOR:"vendor",OTHER:"other"};
function Pb(a,b,c,d,e,f){this.ampdoc=a;this.ja=c;this.pa=d;this.za=e;this.G=f;this.Oa=!!O(a.win)["amp-access-server"];this.gb=!!O(a.win)["amp-access-jwt"];var g=b.type?z().assertEnumValue(Ob,b.type,"access type"):null;g||(g=b.vendor?"vendor":"client");"server"!=g||this.Oa||(z().warn("amp-access",'Experiment "amp-access-server" is not enabled.'),g="client");"client"==g&&this.Oa&&(z().info("amp-access","Forcing access type: SERVER"),g="server");"iframe"!=g||O(this.ampdoc.win)["amp-access-iframe"]||
(z().error("amp-access",'Experiment "amp-access-iframe" is not enabled.'),g="client");this.ea=g;g=b.login;var l={};if(g)if("string"==typeof g)l[""]=g;else if("[object Object]"===ja.call(g))for(var n in g)l[n]=g[n];else B(!1,'"login" must be either a single URL or a map of URLs');for(var r in l)L(l[r],this.G);this.Z=l;this.Ka=b.authorizationFallbackResponse;this.ib=b.namespace||null;this.H=Qb(this,b);this.Ua=za(f,"url-replace");this.kb=Gb.bind(null,a);this.fa=null;a=new m;this.cb=a.promise;this.wa=
a.resolve;this.Ra={};this.I=null;this.Qa=0}h=Pb.prototype;h.getNamespace=function(){return this.ib};h.getType=function(){return this.ea};h.getAdapter=function(){return this.H};h.getAuthResponse=function(){return this.fa};
function Qb(a,b){var c={buildUrl:a.buildUrl.bind(a),collectUrlVars:a.collectUrlVars.bind(a)},d=a.gb&&!0===b.jwt;switch(a.ea){case "client":return d?new sb(a.ampdoc,b,c):new Y(a.ampdoc,b,c);case "iframe":return new Qa(a.ampdoc,b,c);case "server":return d?new sb(a.ampdoc,b,c):new jb(a.ampdoc,b,c);case "vendor":return new xb(a.ampdoc,b);case "other":return new Wa(a.ampdoc,b,c)}throw A().createError("Unsupported access type: ",a.ea);}h.getAdapterConfig=function(){return this.H.getConfig()};
h.whenFirstAuthorized=function(){return this.cb};h.ka=function(){var a=this.ampdoc.getRootNode();return a.documentElement||a.body||a};h.F=function(a){Nb(this.ka(),a)};h.start=function(){A().fine("amp-access","config:",this.ea,this.Z,this.H.getConfig());Rb(this)};h.buildUrl=function(a,b){var c=this;return Sb(this,b).then(function(b){return c.Ua.expandUrlAsync(a,b)})};h.collectUrlVars=function(a,b){var c=this;return Sb(this,b).then(function(b){return c.Ua.collectVars(a,b)})};
function Sb(a,b){return a.ja().then(function(c){var d={READER_ID:c,ACCESS_READER_ID:c};b&&(d.AUTHDATA=function(b){if(a.fa)return Na(a.fa,b)});return d})}
h.runAuthorization=function(a){var b=this;return this.H.isAuthorizationEnabled()?this.H.authorize().catch(function(c){b.F("access-authorization-failed");if(b.Ka&&!a)return z().error("amp-access","Authorization failed: ",c),b.Ka;throw c;}).then(function(a){A().fine("amp-access","Authorization response: ",a);b.fa=a;b.wa();Rb(b);return a}).catch(function(a){z().error("amp-access","Authorization failed: ",a);b.wa();throw a;}):(A().fine("amp-access","Ignore authorization for type=",this.ea),this.wa(),
k())};h.reportViewToServer=function(){var a=this;return this.H.pingback().then(function(){A().fine("amp-access","Pingback complete");a.F("access-pingback-sent")}).catch(function(b){a.F("access-pingback-failed");throw z().createError("Pingback failed: ",b);})};h.getLoginUrl=function(a){return Db(this.ampdoc,a).getLoginUrl()};h.loginWithType=function(a){B(this.Z[a],"Login URL is not configured: %s",a);var b=B(this.Ra[a],"Login URL is not ready: %s",a);return Tb(this,b,a)};
h.loginWithUrl=function(a,b){b=void 0===b?"":b;return Tb(this,a,b)};
function Tb(a,b,c){var d=Date.now();if(a.I&&1E3>d-a.Qa)return a.I;A().fine("amp-access","Start login: ",b,c);Ub(a,c,"started");var e=a.kb(b).then(function(b){A().fine("amp-access","Login dialog completed: ",c,b);a.I=null;b=q(b).success;var d="true"==b||"yes"==b||"1"==b;d?Ub(a,c,"success"):Ub(a,c,"rejected");if(d||!b){a.H.postAction();var e=a.runAuthorization(!0);a.za(e);return e.then(function(){a.pa(0)})}}).catch(function(b){A().fine("amp-access","Login dialog failed: ",c,b);Ub(a,c,"failed");a.I==
e&&(a.I=null);throw b;});a.I=e;a.Qa=d;return a.I}function Ub(a,b,c){a.F("access-login-"+c);b&&a.F("access-login-"+b+"-"+c)}function Rb(a){if(0!=Object.keys(a.Z).length){var b=[],c={},d;for(d in a.Z)c.R=d,b.push(a.buildUrl(a.Z[c.R],!0).then(function(b){return function(c){a.Ra[b.R]=c;return{type:b.R,url:c}}}(c))),c={R:c.R};Promise.all(b)}};var Vb=function(){function a(a,b,c,d){c=c||{};for(d=a.length;d--;c[a[d]]=b);return c}function b(){this.yy={}}var c=[1,3],d=[1,4],e=[1,18],f=[1,19],g=[1,14],l=[1,15],n=[1,16],r=[1,17],Q=[1,21],R=[1,22],t=[5,6,7,10],u=[5,6,7,10,15,16,17,18,19,20,21],D=[5,6,7,10,15,16,17,18,19,20,21,25,27],G={trace:function(){},yy:{},mb:{error:2,result:3,search_condition:4,EOF:5,OR:6,AND:7,NOT:8,"(":9,")":10,predicate:11,comparison_predicate:12,truthy_predicate:13,scalar_exp:14,EQ:15,DEQ:16,NEQ:17,LT:18,LTE:19,GT:20,
GTE:21,atom:22,field_ref:23,literal:24,DOT:25,field_name:26,"[":27,string:28,"]":29,NAME:30,STRING:31,NUMERIC:32,TRUE:33,FALSE:34,NULL:35,$accept:0,$end:1},da:{2:"error",5:"EOF",6:"OR",7:"AND",8:"NOT",9:"(",10:")",15:"EQ",16:"DEQ",17:"NEQ",18:"LT",19:"LTE",20:"GT",21:"GTE",25:"DOT",27:"[",29:"]",30:"NAME",31:"STRING",32:"NUMERIC",33:"TRUE",34:"FALSE",35:"NULL"},Sa:[0,[3,2],[4,3],[4,3],[4,2],[4,3],[4,1],[11,1],[11,1],[12,3],[12,3],[12,3],[12,3],[12,3],[12,3],[12,3],[13,1],[14,1],[14,1],[22,1],[23,
3],[23,4],[23,1],[26,1],[28,1],[24,1],[24,1],[24,1],[24,1],[24,1]],performAction:function(a,b,c,d,e,f){var g=f.length-1;switch(e){case 1:return f[g-1];case 2:this.h=f[g-2]||f[g];break;case 3:this.h=f[g-2]&&f[g];break;case 4:this.h=!f[g];break;case 5:this.h=f[g-1];break;case 6:case 7:case 8:case 17:case 18:case 19:this.h=f[g];break;case 9:this.h=f[g-2]===f[g];break;case 10:throw Error('"==" is not allowed, use "="');case 11:this.h=f[g-2]!==f[g];break;case 12:this.h=typeof f[g-2]==typeof f[g]&&f[g-
2]<f[g];break;case 13:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]<=f[g];break;case 14:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]>f[g];break;case 15:this.h=typeof f[g-2]==typeof f[g]&&f[g-2]>=f[g];break;case 16:this.h=void 0!==f[g]&&null!==f[g]&&""!==f[g]&&0!==f[g]&&!1!==f[g];break;case 20:this.h="[object Object]"==Object.prototype.toString.call(f[g-2])&&f[g-2].hasOwnProperty(f[g])?f[g-2][f[g]]:null;break;case 21:this.h="[object Object]"==Object.prototype.toString.call(f[g-3])&&f[g-3].hasOwnProperty(f[g-
1])?f[g-3][f[g-1]]:null;break;case 22:this.h=void 0!==d[f[g]]?d[f[g]]:null;break;case 23:this.h=a;break;case 24:this.h=a.substring(1,a.length-1);break;case 26:this.h=Number(a);break;case 27:this.h=!0;break;case 28:this.h=!1;break;case 29:this.h=null}},table:[{3:1,4:2,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{1:[3]},{5:[1,20],6:Q,7:R},{4:23,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{4:24,8:c,9:d,11:5,12:6,
13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},a(t,[2,6]),a(t,[2,7]),a(t,[2,8]),a(t,[2,16],{15:[1,25],16:[1,26],17:[1,27],18:[1,28],19:[1,29],20:[1,30],21:[1,31]}),a(u,[2,17]),a(u,[2,18],{25:[1,32],27:[1,33]}),a(u,[2,19]),a(D,[2,22]),a(u,[2,25]),a(u,[2,26]),a(u,[2,27]),a(u,[2,28]),a(u,[2,29]),a(D,[2,23]),a([5,6,7,10,15,16,17,18,19,20,21,29],[2,24]),{1:[2,1]},{4:34,8:c,9:d,11:5,12:6,13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{4:35,8:c,9:d,11:5,12:6,
13:7,14:8,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},a(t,[2,4]),{6:Q,7:R,10:[1,36]},{14:37,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{14:38,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{14:39,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{14:40,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{14:41,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{14:42,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},
{14:43,22:9,23:10,24:11,26:12,28:13,30:e,31:f,32:g,33:l,34:n,35:r},{26:44,30:e},{28:45,31:f},a([5,6,10],[2,2],{7:R}),a(t,[2,3]),a(t,[2,5]),a(t,[2,9]),a(t,[2,10]),a(t,[2,11]),a(t,[2,12]),a(t,[2,13]),a(t,[2,14]),a(t,[2,15]),a(D,[2,20]),{29:[1,46]},a(D,[2,21])],defaultActions:{20:[2,1]},parseError:function(a,b){if(b.recoverable)this.trace(a);else throw a=Error(a),a.hash=b,a;},parse:function(a){function b(){var a=p.lex()||1;"number"!==typeof a&&(a=c.mb[a]||a);return a}var c=this,d=[0],e=[null],f=[],g=
this.table,fb="",l=0,n=0,r=0,t=f.slice.call(arguments,1),p=Object.create(this.lexer),u={yy:{}};for(I in this.yy)Object.prototype.hasOwnProperty.call(this.yy,I)&&(u.yy[I]=this.yy[I]);p.setInput(a,u.yy);u.yy.lexer=p;u.yy.parser=this;"undefined"==typeof p.yylloc&&(p.yylloc={});var D=p.yylloc;f.push(D);var R=p.options&&p.options.ranges;this.parseError="function"===typeof u.yy.parseError?u.yy.parseError:Object.getPrototypeOf(this).parseError;for(var v,G,F,y,J={},fa,C,Q,ha;;){F=d[d.length-1];if(this.defaultActions[F])y=
this.defaultActions[F];else{if(null===v||"undefined"==typeof v)v=b();y=g[F]&&g[F][v]}if("undefined"===typeof y||!y.length||!y[0]){var gb="";ha=[];for(fa in g[F])this.da[fa]&&2<fa&&ha.push("'"+this.da[fa]+"'");gb=p.showPosition?"Parse error on line "+(l+1)+":\n"+p.showPosition()+"\nExpecting "+ha.join(", ")+", got '"+(this.da[v]||v)+"'":"Parse error on line "+(l+1)+": Unexpected "+(1==v?"end of input":"'"+(this.da[v]||v)+"'");this.parseError(gb,{text:p.match,token:this.da[v]||v,line:p.yylineno,loc:D,
expected:ha})}if(y[0]instanceof Array&&1<y.length)throw Error("Parse Error: multiple actions possible at state: "+F+", token: "+v);switch(y[0]){case 1:d.push(v);e.push(p.yytext);f.push(p.yylloc);d.push(y[1]);v=null;G?(v=G,G=null):(n=p.yyleng,fb=p.yytext,l=p.yylineno,D=p.yylloc,0<r&&r--);break;case 2:C=this.Sa[y[1]][1];J.h=e[e.length-C];J.Ia={first_line:f[f.length-(C||1)].first_line,last_line:f[f.length-1].last_line,first_column:f[f.length-(C||1)].first_column,last_column:f[f.length-1].last_column};
R&&(J.Ia.range=[f[f.length-(C||1)].range[0],f[f.length-1].range[1]]);var I=this.performAction.apply(J,[fb,n,l,u.yy,y[1],e,f].concat(t));if("undefined"!==typeof I)return I;C&&(d=d.slice(0,-2*C),e=e.slice(0,-1*C),f=f.slice(0,-1*C));d.push(this.Sa[y[1]][0]);e.push(J.h);f.push(J.Ia);Q=g[d[d.length-2]][d[d.length-1]];d.push(Q);break;case 3:return!0}}}},gc=function(){return{EOF:1,parseError:function(a,b){if(this.yy.parser)this.yy.parser.parseError(a,b);else throw Error(a);},setInput:function(a,b){this.yy=
b||this.yy||{};this._input=a;this._more=this._backtrack=this.done=!1;this.yylineno=this.yyleng=0;this.yytext=this.matched=this.match="";this.conditionStack=["INITIAL"];this.yylloc={first_line:1,first_column:0,last_line:1,last_column:0};this.options.ranges&&(this.yylloc.range=[0,0]);this.offset=0;return this},input:function(){var a=this._input[0];this.yytext+=a;this.yyleng++;this.offset++;this.match+=a;this.matched+=a;a.match(/(?:\r\n?|\n).*/g)?(this.yylineno++,this.yylloc.last_line++):this.yylloc.last_column++;
this.options.ranges&&this.yylloc.range[1]++;this._input=this._input.slice(1);return a},unput:function(a){var b=a.length,c=a.split(/(?:\r\n?|\n)/g);this._input=a+this._input;this.yytext=this.yytext.substr(0,this.yytext.length-b);this.offset-=b;var d=this.match.split(/(?:\r\n?|\n)/g);this.match=this.match.substr(0,this.match.length-1);this.matched=this.matched.substr(0,this.matched.length-1);c.length-1&&(this.yylineno-=c.length-1);a=this.yylloc.range;this.yylloc={first_line:this.yylloc.first_line,last_line:this.yylineno+
1,first_column:this.yylloc.first_column,last_column:c?(c.length===d.length?this.yylloc.first_column:0)+d[d.length-c.length].length-c[0].length:this.yylloc.first_column-b};this.options.ranges&&(this.yylloc.range=[a[0],a[0]+this.yyleng-b]);this.yyleng=this.yytext.length;return this},more:function(){this._more=!0;return this},reject:function(){if(this.options.backtrack_lexer)this._backtrack=!0;else return this.parseError("Lexical error on line "+(this.yylineno+1)+". You can only invoke reject() in the lexer when the lexer is of the backtracking persuasion (options.backtrack_lexer = true).\n"+
this.showPosition(),{text:"",token:null,line:this.yylineno});return this},less:function(a){this.unput(this.match.slice(a))},pastInput:function(){var a=this.matched.substr(0,this.matched.length-this.match.length);return(20<a.length?"...":"")+a.substr(-20).replace(/\n/g,"")},upcomingInput:function(){var a=this.match;20>a.length&&(a+=this._input.substr(0,20-a.length));return(a.substr(0,20)+(20<a.length?"...":"")).replace(/\n/g,"")},showPosition:function(){var a=this.pastInput(),b=Array(a.length+1).join("-");
return a+this.upcomingInput()+"\n"+b+"^"},test_match:function(a,b){var c;if(this.options.backtrack_lexer){var d={yylineno:this.yylineno,yylloc:{first_line:this.yylloc.first_line,last_line:this.last_line,first_column:this.yylloc.first_column,last_column:this.yylloc.last_column},yytext:this.yytext,match:this.match,matches:this.matches,matched:this.matched,yyleng:this.yyleng,offset:this.offset,_more:this._more,_input:this._input,yy:this.yy,conditionStack:this.conditionStack.slice(0),done:this.done};
this.options.ranges&&(d.yylloc.range=this.yylloc.range.slice(0))}if(c=a[0].match(/(?:\r\n?|\n).*/g))this.yylineno+=c.length;this.yylloc={first_line:this.yylloc.last_line,last_line:this.yylineno+1,first_column:this.yylloc.last_column,last_column:c?c[c.length-1].length-c[c.length-1].match(/\r?\n?/)[0].length:this.yylloc.last_column+a[0].length};this.yytext+=a[0];this.match+=a[0];this.matches=a;this.yyleng=this.yytext.length;this.options.ranges&&(this.yylloc.range=[this.offset,this.offset+=this.yyleng]);
this._backtrack=this._more=!1;this._input=this._input.slice(a[0].length);this.matched+=a[0];a=this.performAction.call(this,this.yy,this,b,this.conditionStack[this.conditionStack.length-1]);this.done&&this._input&&(this.done=!1);if(a)return a;if(this._backtrack)for(var e in d)this[e]=d[e];return!1},next:function(){if(this.done)return this.EOF;this._input||(this.done=!0);var a;this._more||(this.match=this.yytext="");for(var b=this._currentRules(),c=0;c<b.length;c++)if((a=this._input.match(this.rules[b[c]]))&&
(!d||a[0].length>d[0].length)){var d=a;var e=c;if(this.options.backtrack_lexer){d=this.test_match(a,b[c]);if(!1!==d)return d;if(this._backtrack)d=!1;else return!1}else if(!this.options.flex)break}return d?(d=this.test_match(d,b[e]),!1!==d?d:!1):""===this._input?this.EOF:this.parseError("Lexical error on line "+(this.yylineno+1)+". Unrecognized text.\n"+this.showPosition(),{text:"",token:null,line:this.yylineno})},lex:function(){var a=this.next();return a?a:this.lex()},begin:function(a){this.conditionStack.push(a)},
popState:function(){return 0<this.conditionStack.length-1?this.conditionStack.pop():this.conditionStack[0]},_currentRules:function(){return this.conditionStack.length&&this.conditionStack[this.conditionStack.length-1]?this.conditions[this.conditionStack[this.conditionStack.length-1]].rules:this.conditions.INITIAL.rules},topState:function(a){a=this.conditionStack.length-1-Math.abs(a||0);return 0<=a?this.conditionStack[a]:"INITIAL"},pushState:function(a){this.begin(a)},stateStackSize:function(){return this.conditionStack.length},
options:{},performAction:function(a,b,c){switch(c){case 1:return 7;case 2:return 6;case 3:return 8;case 4:return 35;case 5:return 33;case 6:return 33;case 7:return 34;case 8:return 34;case 9:return 9;case 10:return 10;case 11:return 27;case 12:return 29;case 13:return"|";case 14:return 19;case 15:return 18;case 16:return 21;case 17:return 20;case 18:return 17;case 19:return 16;case 20:return 15;case 21:return 32;case 22:return 30;case 23:return 31;case 24:return 31;case 25:return 25;case 26:return"INVALID";
case 27:return 5}},rules:[/^(?:\s+)/,/^(?:AND\b)/,/^(?:OR\b)/,/^(?:NOT\b)/,/^(?:NULL\b)/,/^(?:TRUE\b)/,/^(?:true\b)/,/^(?:FALSE\b)/,/^(?:false\b)/,/^(?:\()/,/^(?:\))/,/^(?:\[)/,/^(?:\])/,/^(?:\|)/,/^(?:<=)/,/^(?:<)/,/^(?:>=)/,/^(?:>)/,/^(?:!=)/,/^(?:==)/,/^(?:=)/,/^(?:-?[0-9]+(\.[0-9]+)?\b)/,/^(?:[a-zA-Z_][a-zA-Z0-9_]*)/,/^(?:'[^']*')/,/^(?:"[^"]*")/,/^(?:\.)/,/^(?:.)/,/^(?:$)/],conditions:{INITIAL:{rules:[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27],inclusive:!0}}}}();
G.lexer=gc;b.prototype=G;G.Parser=b;return new b}();function Wb(){this.Pa=this.cache=null}Wb.prototype.evaluate=function(a,b){this.Pa!==b&&(this.Pa=b,this.cache=Object.create(null));if(!na.call(this.cache,a)){var c=this.cache;a:{try{Vb.yy=b;var d=!!Vb.parse(a);break a}finally{Vb.yy=null}d=void 0}c[a]=d}return this.cache[a]};function Xb(){this.m=null}h=Xb.prototype;h.add=function(a){var b=this;this.m||(this.m=[]);this.m.push(a);return function(){b.remove(a)}};h.remove=function(a){this.m&&(a=this.m.indexOf(a),-1<a&&this.m.splice(a,1))};h.removeAll=function(){this.m&&(this.m.length=0)};h.fire=function(a){if(this.m)for(var b=this.m,c=0;c<b.length;c++)(0,b[c])(a)};h.getHandlerCount=function(){return this.m?this.m.length:0};function Yb(a,b){var c=a.getHeadNode(),d=Zb(c,$b(c));if(b){var e=a.getRootNode();if(ac(e,d))b(d);else var f=setInterval(function(){ac(e,d)&&(clearInterval(f),b(d))},4)}}
function Zb(a,b){var c=a.__AMP_CSS_SM;c||(c=a.__AMP_CSS_SM=Object.create(null));var d=bc(a,c,"amp-extension=amp-access");if(d)return d.textContent!==b&&(d.textContent=b),d;var e=(a.ownerDocument||a).createElement("style");e.textContent=b;var f=null;e.setAttribute("amp-extension","amp-access");b=f=bc(a,c,"amp-runtime");(b=void 0===b?null:b)?a.insertBefore(e,b.nextSibling):a.insertBefore(e,a.firstChild);return c["amp-extension=amp-access"]=e}
function bc(a,b,c){return b[c]?b[c]:(a=a.querySelector("style["+c+"]"))?b[c]=a:null}function $b(a){return(a=a.__AMP_CSS_TR)?a("\n/*# sourceURL=/extensions/amp-access/0.1/amp-access.css*/"):"\n/*# sourceURL=/extensions/amp-access/0.1/amp-access.css*/"}function ac(a,b){var c=a.styleSheets;for(a=0;a<c.length;a++)if(c[a].ownerNode==b)return!0;return!1};self.__AMP_ERRORS=self.__AMP_ERRORS||[];function cc(a){var b=this;this.ampdoc=a;Yb(a,function(){});var c=a.getElementById("amp-access");if(this.U=!!c)this.G=c,this.Ta=K(xa(a.win.location)).origin,this.A=X(a.win),this.O=V(a.win,"vsync"),this.Za=Ca(U(a),"cid"),this.Wa=W(a,"viewer"),this.pb=W(a,"viewport"),this.nb=V(a.win,"templates"),this.hb=W(a,"mutator"),this.na=Aa(a.win),this.Aa=null,this.bb=new Wb,this.j=dc(this),c=this.j.map(function(a){return a.whenFirstAuthorized()}),this.ia=!1,this.M=Promise.all(c),this.aa=null,this.Ja=new Xb,this.M.then(function(){b.ia=
!0;b.F("access-authorization-received");b.na&&(b.na.tick("aaa"),b.na.tickSinceVisible("aaav"),b.na.flush())}),a.getRootNode().addEventListener("amp:dom-update",this.jb.bind(this))}h=cc.prototype;h.getAccessReaderId=function(){return this.U?this.ja():null};h.ja=function(){if(!this.Aa){var a=k();this.Aa=this.Za.then(function(b){return b.get({scope:"amp-access",createCookieIfNotPresent:!0},a)})}return this.Aa};h.areFirstAuthorizationsCompleted=function(){return this.ia};h.onApplyAuthorizations=function(a){this.Ja.add(a)};
function dc(a){B(Ia(a.G),'amp-access config should be inside a <script> tag with type="application/json"');var b=Oa(a.G.textContent,function(a){throw z().createError('Failed to parse "amp-access" JSON: '+a);}),c={};if(Array.isArray(b))for(var d=0;d<b.length;d++){var e=b[d].namespace;B(!!e,"Namespace required");B(!c[e],"Namespace already used: "+e);c[e]=b[d]}else c[b.namespace||""]=b;var f=a.ja.bind(a),g=a.pa.bind(a),l=a.za.bind(a);return Object.keys(c).map(function(b){return new Pb(a.ampdoc,c[b],
f,g,l,a.G)})}h.jb=function(a){var b=this;if(this.ia){var c=a.target;return this.M.then(function(){var a=b.combinedResponses();ec(b,c,a)})}};h.getVendorSource=function(a){for(var b=0;b<this.j.length;b++){var c=this.j[b];if("vendor"==c.getType()&&c.getAdapter().getVendorName()==a)return c}B(!1,'Access vendor "%s" can only be used for "type=vendor", but none found',a);throw Error();};h.isEnabled=function(){return this.U};
h.ka=function(){var a=this.ampdoc.getRootNode();return a.documentElement||a.body||a};h.F=function(a){Nb(this.ka(),a)};function fc(a){a.Wa.onBroadcast(function(b){"amp-access-reauthorize"==b.type&&b.origin==a.Ta&&hc(a)})}h.za=function(a){var b=this;this.Ma();a.then(function(){b.ia&&b.M.then(function(){b.ampdoc.whenReady().then(function(){var a=b.ampdoc.getRootNode(),d=b.combinedResponses();return ec(b,a,d)})})})};h.Ma=function(){this.Wa.broadcast(E({type:"amp-access-reauthorize",origin:this.Ta}))};
function hc(a){ic(a,"amp-access-loading",!0);var b=a.ampdoc.whenFirstVisible().then(function(){return Promise.all(a.j.map(function(b){return jc(a,b)}))}).then(function(){ic(a,"amp-access-loading",!1);return a.ampdoc.whenReady().then(function(){var b=a.ampdoc.getRootNode(),d=a.combinedResponses();return ec(a,b,d)})});a.M=b}function jc(a,b){return b.runAuthorization().catch(function(){ic(a,"amp-access-error",!0)})}
h.getAuthdataField=function(a){var b=this;return this.U?this.M.then(function(){var c=b.combinedResponses();c=Na(c,a);return void 0!==c?c:null}):null};function ec(a,b,c){b=b.querySelectorAll("[amp-access]");for(var d=[],e=0;e<b.length;e++)d.push(kc(a,b[e],c));return Promise.all(d).then(function(){a.Ja.fire()})}function kc(a,b,c){var d=b.getAttribute("amp-access"),e=a.bb.evaluate(d,c),f=null;e&&(f=lc(a,b,c));return f?f.then(function(){return mc(a,b,e)}):mc(a,b,e)}
function mc(a,b,c){var d=!b.hasAttribute("amp-access-hide");return c==d?k():a.hb.mutateElement(b,function(){c?b.removeAttribute("amp-access-hide"):b.setAttribute("amp-access-hide","")})}function lc(a,b,c){var d=[],e=b.querySelectorAll("[amp-access-template]");if(0<e.length)for(var f={J:0};f.J<e.length;f={J:f.J},f.J++){var g=nc(a,e[f.J],c).catch(function(a){return function(c){A().error("amp-access","Template failed: ",c,e[a.J],b)}}(f));d.push(g)}return 0<d.length?Promise.all(d):null}
function nc(a,b,c){var d=b,e=null;"TEMPLATE"!=d.tagName&&(e=d,d=e.__AMP_ACCESS__TEMPLATE);return d?a.nb.renderTemplate(d,c).then(function(b){return a.O.mutatePromise(function(){b.setAttribute("amp-access-template","");b.__AMP_ACCESS__TEMPLATE=d;d.parentElement?d.parentElement.replaceChild(b,d):e&&e.parentElement&&e.parentElement.replaceChild(b,e)})}):Promise.reject(Error("template not found"))}
h.pa=function(a){var b=this;this.j.some(function(a){return a.getAdapter().isPingbackEnabled()})&&(this.aa=null,this.ampdoc.whenReady().then(function(){b.ampdoc.isVisible()&&oc(b,a);b.ampdoc.onVisibilityChanged(function(){b.ampdoc.isVisible()&&oc(b,a)})}))};
function oc(a,b){a.aa||(A().fine("amp-access","start view monitoring"),a.aa=pc(a,b).then(function(){return a.M}).then(function(){a.F("access-viewed");for(var b=[],d=0;d<a.j.length;d++)a.j[d].getAdapter().isPingbackEnabled()&&b.push(a.j[d].reportViewToServer());return Promise.all(b)}).catch(function(b){A().fine("amp-access","view cancelled:",b);a.aa=null;throw b;}),a.aa.then(a.Ma.bind(a)))}
function pc(a,b){if(0==b)return k();var c=[];return(new Promise(function(d,e){c.push(a.ampdoc.onVisibilityChanged(function(){a.ampdoc.isVisible()||e(Error("CANCELLED"))}));var f=a.A.delay(d,b);c.push(function(){return a.A.cancel(f)});c.push(a.pb.onScroll(d));c.push(Bb(a.ampdoc.getRootNode(),d))})).then(function(){c.forEach(function(a){return a()})},function(a){c.forEach(function(a){return a()});throw a;})}function ic(a,b,c){a.O.mutate(function(){a.ka().classList.toggle(b,c)})}
h.eb=function(a){if(!a.satisfiesTrust(2))return null;if("login"==a.method)a.event&&a.event.preventDefault(),qc(this,"");else{var b=a.method;(6>b.length?0:0==b.lastIndexOf("login-",0))?(a.event&&a.event.preventDefault(),qc(this,a.method.substring(6))):"refresh"==a.method&&(a.event&&a.event.preventDefault(),hc(this))}return null};h.getSource=function(a){B(0<=a&&a<this.j.length,"Invalid index: %d",a);return this.j[a]};
function qc(a,b){var c=b.indexOf("-"),d=1==a.j.length,e=-1<c?b.substring(0,c):b,f=a.j.filter(function(a){return a.getNamespace()==e});if(f.length){var g=-1<c?b.substring(c+1):"";f[0].loginWithType(g)}else B(d,"Login must match namespace: %s",e),a.j[0].loginWithType(b)}h.combinedResponses=function(){if(1==this.j.length&&!this.j[0].getNamespace())return this.j[0].getAuthResponse()||{};var a={};this.j.forEach(function(b){return a[b.getNamespace()]=b.getAuthResponse()});return a};
(function(a){a.registerServiceForDoc("access",function(a){a=new cc(a);if(a.U){za(a.G,"action").installActionHandler(a.G,a.eb.bind(a));for(var b=0;b<a.j.length;b++)a.j[b].start();hc(a);a.pa(2E3);fc(a)}else z().info("amp-access",'Access is disabled - no "id=amp-access" element');return a})})(self.AMP);
})});

//# sourceMappingURL=amp-access-0.1.js.map
